image: ubuntu:latest

stages:
  - build
  - test

build:
    stage: build
    before_script:
        - apt-get update && apt-get install -y cmake g++ make libboost-all-dev
    script:
        - echo "Building project..."
        - mkdir -p cmake-build-Debug/output
        - cmake -Bcmake-build-Debug/udemy1 -H./udemy1
        - cd cmake-build-Debug/udemy1 && make -j`nproc`
        - cd -
        - cmake -Bcmake-build-Debug/relearn_dl -H./relearn_dl
        - cd cmake-build-Debug/relearn_dl && make -j`nproc`
        - cd -
        - cmake -Bcmake-build-Debug/relearn_sl -H./relearn_sl
        - cd cmake-build-Debug/relearn_sl && make  -j`nproc`
        - cd -
        - cmake -Bcmake-build-Debug/relearn -H./relearn
        - cd cmake-build-Debug/relearn && make -j`nproc`
    artifacts:
        untracked: false
        when: on_success
        expire_in: 3 days
        paths:
            - cmake-build-Debug/output/

test:
    stage: test
    script:
        - echo "Running output file..."
        - cd cmake-build-Debug/output
        - ./relearn
    dependencies:
        - build
