stages:
  - build
  - test

build:
    stage: build
    image: alpine:latest
    before_script:
        - echo "Installing GCC, boost-dev, CMake, make..."
        - apk add --no-cache gcc g++ cmake boost-dev git
        - echo "Downloading GoogleTestFramework.."
        - git clone https://github.com/google/googletest.git
        - echo "Installing GoogleTestFramework..."
        - cd googletest
        - cmake -Bbuild 
        - cmake --build build --target install -j`nproc`
    script:
        - echo $PATH
        - echo "Building project..."
        - mkdir -p cmake-build-Debug/output
        - cmake cmake-build-Debug -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -Bcmake-build-Debug -H.
        - cmake --build cmake-build-Debug -j`nproc`
    artifacts:
        untracked: false
        when: on_success
        expire_in: 1 days
        paths:
            - cmake-build-Debug/output/

test:
    stage: test
    image: alpine:latest
    before_script:
    - echo "Installing boost-dev..."
    - apk add --no-cache boost-dev
    script:
        - echo "Running output file..."
        - ./cmake-build-Debug/output/unittest-relearn
    dependencies:
        - build

