image: ubuntu:latest

stages:
  - build

before_script:
  - apt-get update && apt-get install -y cmake g++ make

build:
  stage: build
  script:
    - mkdir -p cmake-build-Debug/output
    - cmake -Bcmake-build-Debug/udemy1 -H./udemy1
    - cmake -Bcmake-build-Debug/relearn_dl -H./relearn_dl
    - cmake -Bcmake-build-Debug/relearn_sl -H./relearn_sl
    - cmake -Bcmake-build-Debug/relearn -H./relearn
    - cd cmake-build-Debug/udemy1 && make -j`nproc`
    - cd -
    - cd cmake-build-Debug/relearn_dl && make -j`nproc`
    - cd -
    - cd cmake-build-Debug/relearn_sl && make  -j`nproc`
    - cd -
    - cd cmake-build-Debug/relearn && make -j`nproc`
    - cd -

test:
    stage: test
    script:
        - cd cmake-build-Debug/output
        - ./relearn



    