stages:
  - build
  - test

build:
    stage: build
    image: alpine:latest
    before_script:
        - echo "Installing GCC, boost-dev, CMake, make..."
        - apk add --no-cache gcc g++ cmake boost-dev make
    script:
        - echo $PATH
        - echo "Building project..."
        - mkdir -p cmake-build-Debug/output
        - cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -Bcmake-build-Debug/relearn -H./relearn
        - cd cmake-build-Debug/relearn && make -j`nproc`
    artifacts:
        untracked: false
        when: on_success
        expire_in: 1 days
        paths:
            - cmake-build-Debug/output/

test:
    stage: test
    image: alpine:latest
    before_script:
    - echo "Installing boost-dev..."
    - apk add --no-cache boost-dev
    script:
        - echo "Running output file..."
        - cd cmake-build-Debug/output
        - ./relearn
    dependencies:
        - build
