stages:
  - build
  - test

build:
    stage: build
    image: alpine:latest
    before_script:
        - echo "Installing GCC, CMake, make and libboost-dev..."
        - apk add --no-cache gcc cmake libboost-dev make
    script:
        - echo "Building project..."
        - mkdir -p cmake-build-Debug/output
        - cmake -Bcmake-build-Debug/relearn -H./relearn
        - cd cmake-build-Debug/relearn && make -j`nproc`
    artifacts:
        untracked: false
        when: on_success
        expire_in: 1 days
        paths:
            - cmake-build-Debug/output/

test:
    stage: test
    image: alpine:latest
    script:
        - echo "Running output file..."
        - cd cmake-build-Debug/output
        - ./relearn
    dependencies:
        - build
